version: '2'
services:
  db:
    build: db
    image: mcmoe/mssqldocker
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd2
    ports:
      - 1433:1433
    container_name: sampledb
    volumes:
      - ./docker/samples-db/data:/var/opt/mssql