# Server conf
server:
  port: 8811

# App conf
check-user-scopes: false

# Spring conf
spring:
  application:
    name: auth-service
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:sqlserver://${app.db.server};databaseName=${app.db.name}
    username: ${app.db.user}
    password: ${app.db.psw}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#SLF4J
logging:
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    com.maestro.app.sample.ms.auth: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"