# Server Section
server:
  port: 8813

# Spring conf
spring:
  application:
    name: service2
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:sqlserver://${app.db.server};databaseName=${app.db.name}
    username: ${app.db.user}
    password: ${app.db.psw}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# Ribbon conf
ribbon:
  # Connect timeout used by HttpClient
  ConnectTimeout: 12000
  # Read timeout used by HttpClient
  ReadTimeout: 30000
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 1
  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 1
  eager-load:
    enabled: true

#SLF4J
logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    com.maestro.app.sample1.ms: ${app.telemetry.level}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"